
@register(outgoing=True, pattern='^.geez(?: |$)(.*)')
async def typewriter(typew):
    typew.pattern_match.group(1)
    await typew.edit("**Afreal Peler☑️**")
    await typew.edit("**Afreal Peler✅**")
    sleep(1)
    await typew.edit("**Anggra Gilaa☑️**")
    await typew.edit("**Anggra Gilaa✅**")
    sleep(2)
    await typew.edit("**Eggyol Depresi☑️**")
    await typew.edit("**Eggyol Depresi✅**")
    sleep(2)
    await typew.edit("**Yunus Gajelas☑️**")
    await typew.edit("**Yunus Gajelas✅**")
    sleep(2)
    await typew.edit("**Anggra Babi!☑️**")
    await typew.edit("**Anggra Babi!✅**")
    sleep(2)
    await typew.edit("**Ceca Jelek!!☑️**")
    await typew.edit("**Ceca Jelek!!✅**")
    sleep(2)
    await typew.edit("**Bintang,MengRibet☑️**")
    await typew.edit("**Bintang,MengRibet✅**")
    sleep(2)
    await typew.edit("**Afreal,Mengintil☑️**")
    await typew.edit("**Afreal,Mengintil✅**")
    sleep(3)
    await typew.edit("**CUMA SKYZO YANG BENER!**")
